# Generated by Django 4.2.7 on 2026-04-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_add_missing_comment_fields_safe'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savedpost',
            index=models.Index(fields=['user', 'reel'], name='api_savedpo_user_id_62e26e_idx'),
        ),
        migrations.AddIndex(
            model_name='savedpost',
            index=models.Index(fields=['reel', 'user'], name='api_savedpo_reel_id_329280_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['reel', 'user'], name='api_vote_reel_id_c007e7_idx'),
        ),
    ]
