import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    // Navigation
    home: "Home",
    forYou: "For You",
    search: "Search",
    explore: "Explore",
    reels: "Reels",
    followingTab: "Following",
    inbox: "Inbox",
    messages: "Messages",
    notifications: "Notifications",
    bookmarks: "Bookmarks",
    create: "Create",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    login: "Login",
    signUp: "Sign Up",
    campaigns: "Campaigns",
    winners: "Winners",
    suggestions: "Suggestions",
    recommended: "Recommended for You",
    
    // Actions
    like: "Like",
    comment: "Comment",
    share: "Share",
    save: "Save",
    saved: "Saved",
    follow: "Follow",
    following: "Following",
    unfollow: "Unfollow",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    post: "Post",
    
    // Profile
    posts: "Posts",
    followers: "Followers",
    followingCount: "Following",
    editProfile: "Edit Profile",
    
    // Settings
    account: "Account",
    accountSettings: "Account Settings",
    manageAccount: "Manage your account information",
    notificationsSettings: "Notifications",
    manageNotifications: "Manage your notification preferences",
    privacy: "Privacy & Security",
    controlPrivacy: "Control your privacy settings",
    appearance: "Appearance",
    customizeAppearance: "Customize how FlipStar looks",
    language: "Language",
    chooseLanguage: "Choose your preferred language",
    help: "Help & Support",
    getHelp: "Get help and support",
    darkMode: "Dark Mode",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password (min 8 characters)",
    confirmPassword: "Confirm New Password",
    updatePassword: "Update Password",
    downloadData: "Download Your Data",
    downloadDataDesc: "Download a copy of all your posts, comments, and profile data",
    deleteAccount: "Delete Account",
    dangerZone: "Danger Zone",
    deleteWarning: "Once you delete your account, there is no going back. Please be certain.",
    basicInfo: "Basic Information",
    username: "Username",
    email: "Email",
    dataManagement: "Data Management",
    success: "Success",
    settingsSaved: "Settings saved successfully!",
    error: "Error",
    passwordMismatch: "New passwords do not match!",
    passwordTooShort: "Password must be at least 8 characters!",
    passwordChanged: "Password changed successfully!",
    passwordChangeFailed: "Failed to change password",
    deleteConfirm: "Are you sure you want to delete your account? This action cannot be undone!",
    finalConfirm: "This will permanently delete all your data. Are you absolutely sure?",
    accountDeleted: "Account Deleted",
    accountDeleting: "Account deletion initiated. You will be logged out.",
    downloadInitiated: "Download Initiated",
    downloadEmail: "Your data download has been initiated. You will receive an email with a download link.",
    notificationEnabled: "Notification Enabled",
    willReceive: "You will now receive notifications for",
    privacyUpdated: "Privacy Updated",
    privacySettingChanged: "Privacy setting",
    enabled: "has been enabled",
    disabled: "has been disabled",
    darkEnabled: "Dark theme enabled",
    lightEnabled: "Light theme enabled",
    receiveNotifications: "Receive notifications for",
    privateAccountDesc: "Only approved followers can see your posts",
    showActivityDesc: "Show your activity status to others",
    allowMessagesDesc: "Allow others to send you messages",
    helpCenter: "Help Center",
    reportProblem: "Report a Problem",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    version: "Version",
    cancel: "Cancel",
    confirm: "Confirm",
    ok: "OK",
    likes: "Likes",
    comments: "Comments",
    follows: "Follows",
    messages: "Messages",
    
    // Post
    caption: "Caption",
    hashtags: "Hashtags",
    uploadMedia: "Upload Media",
    
    // Common
    loading: "Loading...",
    noResults: "No results found",
    error: "An error occurred",
  },
  am: {
    // Navigation (Amharic)
    home: "መነሻ",
    forYou: "ለእርስዎ",
    search: "ፈልግ",
    explore: "ያስሱ",
    reels: "ሪልስ",
    followingTab: "እየተከተሉ",
    inbox: "መልዕክቶች",
    messages: "መልዕክቶች",
    notifications: "ማሳወቂያዎች",
    bookmarks: "የተቀመጡ",
    create: "ይፍጠሩ",
    profile: "መገለጫ",
    settings: "ቅንብሮች",
    logout: "ውጣ",
    login: "ግባ",
    signUp: "ይመዝገቡ",
    campaigns: "ዘመቻዎች",
    winners: "አሸናፊዎች",
    suggestions: "ጥቆማዎች",
    recommended: "ለእርስዎ የሚመከር",
    
    // Actions
    like: "አስደስት",
    comment: "አስተያየት",
    share: "አጋራ",
    save: "አስቀምጥ",
    saved: "ተቀምጧል",
    follow: "ተከተል",
    following: "እየተከተሉ",
    unfollow: "አትከተል",
    edit: "አርትዕ",
    delete: "ሰርዝ",
    cancel: "ሰርዝ",
    post: "ለጥፍ",
    
    // Profile
    posts: "ልጥፎች",
    followers: "ተከታዮች",
    followingCount: "እየተከተሉ",
    editProfile: "መገለጫ አርትዕ",
    
    // Settings
    account: "መለያ",
    accountSettings: "የመለያ ቅንብሮች",
    manageAccount: "የመለያ መረጃዎን ያስተዳድሩ",
    notificationsSettings: "ማሳወቂያዎች",
    manageNotifications: "የማሳወቂያ ምርጫዎችዎን ያስተዳድሩ",
    privacy: "ግላዊነት እና ደህንነት",
    controlPrivacy: "የግላዊነት ቅንብሮችዎን ያስተዳድሩ",
    appearance: "መልክ",
    customizeAppearance: "FlipStar እንዴት እንደሚመስል ያቀናብሩ",
    language: "ቋንቋ",
    chooseLanguage: "የሚፈልጉትን ቋንቋ ይምረጡ",
    help: "እገዛ እና ድጋፍ",
    getHelp: "እገዛ እና ድጋፍ ያግኙ",
    darkMode: "ጨለማ ሁነታ",
    changePassword: "የይለፍ ቃል ቀይር",
    currentPassword: "አሁን ያለው የይለፍ ቃል",
    newPassword: "አዲስ የይለፍ ቃል (አንድ በኋላ 8 ቁምፊ)",
    confirmPassword: "አዲስ የይለፍ ቃል ያረጋግጡ",
    updatePassword: "የይለፍ ቃል ያዘምኑ",
    downloadData: "መረጃዎን አውርድ",
    downloadDataDesc: "ሁሉንም ልጥፎችዎ፣ አስተያየቶች እና የመገለጫ መረጃዎን ይውርዱ",
    deleteAccount: "መለያ ሰርዝ",
    dangerZone: "አደጋ አካባቢ",
    deleteWarning: "መለያዎን ካስወገዱ መመለስ የለም። እባክዎ ያረጋግጡ።",
    basicInfo: "መሰረታዊ መረጃ",
    username: "የተጠቃሚ ስም",
    email: "ኢሜይል",
    dataManagement: "የመረጃ አስተዳደር",
    success: "አስተማማም",
    settingsSaved: "ቅንብሮች በተሳካ ሁኔታ ተቀምጠዋል!",
    error: "ስህተት",
    passwordMismatch: "አዲስ የይለፍ ቃሎች አይደሉም!",
    passwordTooShort: "የይለፍ ቃል ቢያንስ 8 ቁምፊ መሆን አለበት!",
    passwordChanged: "የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል!",
    passwordChangeFailed: "የይለፍ ቃል መቀየር አልተሳካም",
    deleteConfirm: "መለያዎን ለማጥፋት እርግጠኛ ነዎት? ይህ ተግባር አይቀርም!",
    finalConfirm: "ይህ ሁሉንም መረጃዎን በቋሚነት ያጠፋል። በጭራት እርግጠኛ ነዎት?",
    accountDeleted: "መለያ ተሰርዟል",
    accountDeleting: "መለያ መሰርያ ተምሯል። ይውጡ።",
    downloadInitiated: "የወረደ ተጀምሯል",
    downloadEmail: "የመረጃ ውርድዎ ተምሯል። የወረደ አገናኝ እንደ ኢሜይል ያገኙታል።",
    notificationEnabled: "ማሳወቂያ ተካትቷል",
    willReceive: "ለዚያ ማሳወቂያ ያገኙታል",
    privacyUpdated: "ግላዊነት ተዘምኗል",
    privacySettingChanged: "የግላዊነት ቅንብር",
    enabled: "ተካትቷል",
    disabled: "ተሰርዟል",
    darkEnabled: "ጨለማ ገጽታ ተካትቷል",
    lightEnabled: "ብርሃን ገጽታ ተካትቷል",
    receiveNotifications: "ለማሳወቂያ ያገኙ",
    privateAccountDesc: "የተፈቀዱ ተከታዮች ብቻ ልጥፎችዎን ማየት ይችላሉ",
    showActivityDesc: "የእርስዎ ንቁ ሁኔታ ለአጭር ጊዜ ለሌሎች አሳይ",
    allowMessagesDesc: "ሌሎች መልዕክቶች ለመላክ ፍቀድ",
    helpCenter: "የእገዛ ማዕከል",
    reportProblem: "ችግር ይዘምኑ",
    termsOfService: "የአገልግሎት ውል",
    privacyPolicy: "የግላዊነት ፖሊሲ",
    version: "ስሪት",
    cancel: "ሰርዝ",
    confirm: "አረጋግጥ",
    ok: "እሺ",
    likes: "አስደስቶች",
    comments: "አስተያየቶች",
    follows: "ተከታዮች",
    messages: "መልዕክቶች",
    
    // Post
    caption: "መግለጫ",
    hashtags: "ሃሽታጎች",
    uploadMedia: "ሚዲያ ይስቀሉ",
    
    // Common
    loading: "በመጫን ላይ...",
    noResults: "ምንም ውጤት አልተገኘም",
    error: "ስህተት ተከስቷል",
  },
  es: {
    // Navigation (Spanish)
    home: "Inicio",
    forYou: "Para Ti",
    search: "Buscar",
    explore: "Explorar",
    reels: "Reels",
    followingTab: "Siguiendo",
    inbox: "Bandeja",
    messages: "Mensajes",
    notifications: "Notificaciones",
    bookmarks: "Guardados",
    create: "Crear",
    profile: "Perfil",
    settings: "Ajustes",
    logout: "Cerrar Sesión",
    login: "Iniciar Sesión",
    signUp: "Registrarse",
    campaigns: "Campañas",
    winners: "Ganadores",
    suggestions: "Sugerencias",
    recommended: "Recomendado para Ti",
    
    // Actions
    like: "Me Gusta",
    comment: "Comentar",
    share: "Compartir",
    save: "Guardar",
    saved: "Guardado",
    follow: "Seguir",
    following: "Siguiendo",
    unfollow: "Dejar de Seguir",
    edit: "Editar",
    delete: "Eliminar",
    cancel: "Cancelar",
    post: "Publicar",
    
    // Profile
    posts: "Publicaciones",
    followers: "Seguidores",
    followingCount: "Siguiendo",
    editProfile: "Editar Perfil",
    
    // Settings
    account: "Cuenta",
    accountSettings: "Configuración de Cuenta",
    manageAccount: "Gestionar la información de tu cuenta",
    notificationsSettings: "Notificaciones",
    manageNotifications: "Gestionar tus preferencias de notificación",
    privacy: "Privacidad y Seguridad",
    controlPrivacy: "Controlar tu configuración de privacidad",
    appearance: "Apariencia",
    customizeAppearance: "Personalizar cómo se ve FlipStar",
    language: "Idioma",
    chooseLanguage: "Elige tu idioma preferido",
    help: "Ayuda y Soporte",
    getHelp: "Obtener ayuda y soporte",
    darkMode: "Modo Oscuro",
    changePassword: "Cambiar Contraseña",
    currentPassword: "Contraseña Actual",
    newPassword: "Nueva Contraseña (mínimo 8 caracteres)",
    confirmPassword: "Confirmar Nueva Contraseña",
    updatePassword: "Actualizar Contraseña",
    downloadData: "Descargar Tus Datos",
    downloadDataDesc: "Descargar una copia de todas tus publicaciones, comentarios y datos de perfil",
    deleteAccount: "Eliminar Cuenta",
    dangerZone: "Zona de Peligro",
    deleteWarning: "Una vez que elimines tu cuenta, no hay vuelta atrás. Por favor, ten cuidado.",
    basicInfo: "Información Básica",
    username: "Nombre de Usuario",
    email: "Correo Electrónico",
    dataManagement: "Gestión de Datos",
    success: "Éxito",
    settingsSaved: "¡Configuración guardada exitosamente!",
    error: "Error",
    passwordMismatch: "¡Las nuevas contraseñas no coinciden!",
    passwordTooShort: "¡La contraseña debe tener al menos 8 caracteres!",
    passwordChanged: "¡Contraseña cambiada exitosamente!",
    passwordChangeFailed: "Error al cambiar la contraseña",
    deleteConfirm: "¿Estás seguro de que quieres eliminar tu cuenta? ¡Esta acción no se puede deshacer!",
    finalConfirm: "Esto eliminará permanentemente todos tus datos. ¿Estás absolutamente seguro?",
    accountDeleted: "Cuenta Eliminada",
    accountDeleting: "Eliminación de cuenta iniciada. Serás desconectado.",
    downloadInitiated: "Descarga Iniciada",
    downloadEmail: "Tu descarga de datos ha sido iniciada. Recibirás un correo con el enlace de descarga.",
    notificationEnabled: "Notificación Habilitada",
    willReceive: "Ahora recibirás notificaciones para",
    privacyUpdated: "Privacidad Actualizada",
    privacySettingChanged: "La configuración de privacidad",
    enabled: "ha sido habilitada",
    disabled: "ha sido deshabilitada",
    darkEnabled: "Tema oscuro habilitado",
    lightEnabled: "Tema claro habilitado",
    receiveNotifications: "Recibir notificaciones para",
    privateAccountDesc: "Solo seguidores aprobados pueden ver tus publicaciones",
    showActivityDesc: "Mostrar tu estado de actividad a otros",
    allowMessagesDesc: "Permitir que otros te envíen mensajes",
    helpCenter: "Centro de Ayuda",
    reportProblem: "Reportar un Problema",
    termsOfService: "Términos de Servicio",
    privacyPolicy: "Política de Privacidad",
    version: "Versión",
    cancel: "Cancelar",
    confirm: "Confirmar",
    ok: "OK",
    likes: "Me Gusta",
    comments: "Comentarios",
    follows: "Seguidores",
    messages: "Mensajes",
    
    // Post
    caption: "Descripción",
    hashtags: "Hashtags",
    uploadMedia: "Subir Medios",
    
    // Common
    loading: "Cargando...",
    noResults: "No se encontraron resultados",
    error: "Ocurrió un error",
  },
  fr: {
    // Navigation (French)
    home: "Accueil",
    forYou: "Pour Vous",
    search: "Rechercher",
    explore: "Explorer",
    reels: "Reels",
    followingTab: "Abonnements",
    inbox: "Boîte",
    messages: "Messages",
    notifications: "Notifications",
    bookmarks: "Enregistrés",
    create: "Créer",
    profile: "Profil",
    settings: "Paramètres",
    logout: "Déconnexion",
    login: "Connexion",
    signUp: "S'inscrire",
    campaigns: "Campagnes",
    winners: "Gagnants",
    suggestions: "Suggestions",
    recommended: "Recommandé pour Vous",
    
    // Actions
    like: "J'aime",
    comment: "Commenter",
    share: "Partager",
    save: "Enregistrer",
    saved: "Enregistré",
    follow: "Suivre",
    following: "Abonné",
    unfollow: "Ne plus suivre",
    edit: "Modifier",
    delete: "Supprimer",
    cancel: "Annuler",
    post: "Publier",
    
    // Profile
    posts: "Publications",
    followers: "Abonnés",
    followingCount: "Abonnements",
    editProfile: "Modifier le Profil",
    
    // Settings
    account: "Compte",
    accountSettings: "Paramètres du Compte",
    manageAccount: "Gérer les informations de votre compte",
    notificationsSettings: "Notifications",
    manageNotifications: "Gérer vos préférences de notification",
    privacy: "Confidentialité et Sécurité",
    controlPrivacy: "Contrôler vos paramètres de confidentialité",
    appearance: "Apparence",
    customizeAppearance: "Personnaliser l'apparence de FlipStar",
    language: "Langue",
    chooseLanguage: "Choisissez votre langue préférée",
    help: "Aide et Support",
    getHelp: "Obtenir de l'aide et du support",
    darkMode: "Mode Sombre",
    changePassword: "Changer le Mot de Passe",
    currentPassword: "Mot de Passe Actuel",
    newPassword: "Nouveau Mot de Passe (min 8 caractères)",
    confirmPassword: "Confirmer le Nouveau Mot de Passe",
    updatePassword: "Mettre à Jour le Mot de Passe",
    downloadData: "Télécharger Vos Données",
    downloadDataDesc: "Télécharger une copie de toutes vos publications, commentaires et données de profil",
    deleteAccount: "Supprimer le Compte",
    dangerZone: "Zone de Danger",
    deleteWarning: "Une fois que vous supprimez votre compte, il n'y a pas de retour en arrière. Soyez certain.",
    basicInfo: "Informations de Base",
    username: "Nom d'utilisateur",
    email: "E-mail",
    dataManagement: "Gestion des Données",
    success: "Succès",
    settingsSaved: "Paramètres enregistrés avec succès!",
    error: "Erreur",
    passwordMismatch: "Les nouveaux mots de passe ne correspondent pas!",
    passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères!",
    passwordChanged: "Mot de passe changé avec succès!",
    passwordChangeFailed: "Échec du changement de mot de passe",
    deleteConfirm: "Êtes-vous sûr de vouloir supprimer votre compte? Cette action ne peut être annulée!",
    finalConfirm: "Cela supprimera définitivement toutes vos données. Êtes-vous absolument sûr?",
    accountDeleted: "Compte Supprimé",
    accountDeleting: "Suppression du compte initiée. Vous serez déconnecté.",
    downloadInitiated: "Téléchargement Initié",
    downloadEmail: "Votre téléchargement de données a été initié. Vous recevrez un e-mail avec le lien de téléchargement.",
    notificationEnabled: "Notification Activée",
    willReceive: "Vous recevrez maintenant des notifications pour",
    privacyUpdated: "Confidentialité Mise à Jour",
    privacySettingChanged: "Le paramètre de confidentialité",
    enabled: "a été activé",
    disabled: "a été désactivé",
    darkEnabled: "Thème sombre activé",
    lightEnabled: "Thème clair activé",
    receiveNotifications: "Recevoir des notifications pour",
    privateAccountDesc: "Seuls les abonnés approuvés peuvent voir vos publications",
    showActivityDesc: "Montrer votre statut d'activité aux autres",
    allowMessagesDesc: "Autoriser les autres à vous envoyer des messages",
    helpCenter: "Centre d'Aide",
    reportProblem: "Signaler un Problème",
    termsOfService: "Conditions d'Utilisation",
    privacyPolicy: "Politique de Confidentialité",
    version: "Version",
    cancel: "Annuler",
    confirm: "Confirmer",
    ok: "OK",
    likes: "J'aime",
    comments: "Commentaires",
    follows: "Abonnés",
    messages: "Messages",
    
    // Post
    caption: "Légende",
    hashtags: "Hashtags",
    uploadMedia: "Télécharger des Médias",
    
    // Common
    loading: "Chargement...",
    noResults: "Aucun résultat trouvé",
    error: "Une erreur s'est produite",
  },
  ar: {
    // Navigation (Arabic)
    home: "الرئيسية",
    forYou: "لك",
    search: "بحث",
    explore: "استكشف",
    reels: "ريلز",
    followingTab: "المتابَعون",
    inbox: "البريد",
    messages: "الرسائل",
    notifications: "الإشعارات",
    bookmarks: "المحفوظات",
    create: "إنشاء",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    login: "تسجيل الدخول",
    signUp: "التسجيل",
    campaigns: "الحملات",
    winners: "الفائزون",
    suggestions: "الاقتراحات",
    recommended: "موصى به لك",
    
    // Actions
    like: "إعجاب",
    comment: "تعليق",
    share: "مشاركة",
    save: "حفظ",
    saved: "محفوظ",
    follow: "متابعة",
    following: "متابَع",
    unfollow: "إلغاء المتابعة",
    edit: "تعديل",
    delete: "حذف",
    cancel: "إلغاء",
    post: "نشر",
    
    // Profile
    posts: "المنشورات",
    followers: "المتابعون",
    followingCount: "المتابَعون",
    editProfile: "تعديل الملف الشخصي",
    
    // Settings
    account: "الحساب",
    accountSettings: "إعدادات الحساب",
    manageAccount: "إدارة معلومات حسابك",
    notificationsSettings: "الإشعارات",
    manageNotifications: "إدارة تفضيلات الإشعارات",
    privacy: "الخصوصية والأمان",
    controlPrivacy: "التحكم في إعدادات الخصوصية",
    appearance: "المظهر",
    customizeAppearance: "تخصيص مظهر FlipStar",
    language: "اللغة",
    chooseLanguage: "اختر اللغة المفضلة",
    help: "المساعدة والدعم",
    getHelp: "الحصول على المساعدة والدعم",
    darkMode: "الوضع الداكن",
    changePassword: "تغيير كلمة المرور",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة (8 أحرف على الأقل)",
    confirmPassword: "تأكيد كلمة المرور الجديدة",
    updatePassword: "تحديث كلمة المرور",
    downloadData: "تنزيل بياناتك",
    downloadDataDesc: "تنزيل نسخة من جميع منشوراتك وتعليقاتك وبيانات ملفك الشخصي",
    deleteAccount: "حذف الحساب",
    dangerZone: "منطقة الخطر",
    deleteWarning: "بمجرد حذف حسابك، لا عودة. يرجى التأكد.",
    basicInfo: "المعلومات الأساسية",
    username: "اسم المستخدم",
    email: "البريد الإلكتروني",
    dataManagement: "إدارة البيانات",
    success: "نجاح",
    settingsSaved: "تم حفظ الإعدادات بنجاح!",
    error: "خطأ",
    passwordMismatch: "كلمات المرور الجديدة غير متطابقة!",
    passwordTooShort: "يجب أن تكون كلمة المرور 8 أحرف على الأقل!",
    passwordChanged: "تم تغيير كلمة المرور بنجاح!",
    passwordChangeFailed: "فشل تغيير كلمة المرور",
    deleteConfirm: "هل أنت متأكد أنك تريد حذف حسابك؟ هذا الإجراء لا يمكن التراجع عنه!",
    finalConfirm: "سيؤدي هذا إلى حذف جميع بياناتك بشكل دائم. هل أنت متأكد تماماً؟",
    accountDeleted: "تم حذف الحساب",
    accountDeleting: "تم بدء حذف الحساب. سيتم تسجيل الخروج.",
    downloadInitiated: "تم بدء التنزيل",
    downloadEmail: "تم بدء تنزيل بياناتك. ستصلك رسالة بريد إلكتروني مع رابط التنزيل.",
    notificationEnabled: "تم تمكين الإشعار",
    willReceive: "ستتلقى الآن إشعارات لـ",
    privacyUpdated: "تم تحديث الخصوصية",
    privacySettingChanged: "إعداد الخصوصية",
    enabled: "تم تمكينه",
    disabled: "تم تعطيله",
    darkEnabled: "تم تمكين السمة الداكنة",
    lightEnabled: "تم تمكين السمة الفاتحة",
    receiveNotifications: "تلقي إشعارات لـ",
    privateAccountDesc: "يمكن فقط للمتابعين المعتمدين رؤية منشوراتك",
    showActivityDesc: "إظهار حالة نشاطك للآخرين",
    allowMessagesDesc: "السماح للآخرين بإرسال رسائل إليك",
    helpCenter: "مركز المساعدة",
    reportProblem: "الإبلاغ عن مشكلة",
    termsOfService: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
    version: "الإصدار",
    cancel: "إلغاء",
    confirm: "تأكيد",
    ok: "موافق",
    likes: "إعجابات",
    comments: "تعليقات",
    follows: "متابعون",
    messages: "رسائل",
    
    // Post
    caption: "التعليق",
    hashtags: "الوسوم",
    uploadMedia: "تحميل الوسائط",
    
    // Common
    loading: "جارٍ التحميل...",
    noResults: "لم يتم العثور على نتائج",
    error: "حدث خطأ",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    
    // Set document direction for RTL languages
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
